### PR TITLE
feat: support `unwatchFile`

### PR DESCRIPTION
**Pull request by aleung**
- implement `unwatchFile`
- add unit test case for it
- format the code with prettier

### CODE REVIEW

**Comment by tstordyallison** [comment]
+1 for this if anyone is around to review...

I stumbled across the error and it let me here!

**Review by G-Rath — APPROVED** [review]

**Comment by G-Rath** [comment]
@aleung it looks like your test might be a bit unstable - would you be willing to look into that for us?

**Comment by aleung** [comment]
@G-Rath The test failed in "union › Union › Streams › can create Writable Streams" but I didn't change this one. The test added in my PR is "union › Union › sync methods › watch() › can watchFile and unwatchFile". Anyway, I'll try to run test locally to verify it.

**Comment by G-Rath** [comment]
@aleung yeah that failure is a different one. The failure from this PR seems to only happen when you run the tests multiple times due to files being created so it looks like it behaves differently on subsequent runs.

Thanks for looking into this! I'm a bit slammed at the moment so any time you can spare is appreciated 😊

**Comment by G-Rath** [comment]
@aleung it looks like the issue was just timing - [adding another call to `sleep` between setting up the watcher and the initial writing to file](https://github.com/streamich/unionfs/pull/740/files#diff-31714cfb4e839b8ea89ec8f8b00912b3e494ea92366bb13ac85e1500fa76e5b2R78) looks to have resolved the issue.

**Comment by aleung** [comment]
@G-Rath Great. Do you need any more action from me?

**Comment by G-Rath** [comment]
@aleung at the time no, but now it looks like after a general lockfile update (#758) a new issue has start occuring:

```
● union › Union › sync methods › watch() › should create a watcher

    expect(jest.fn()).toBeCalledWith(...expected)

    Expected: "change", "/tmp/foo.js"
    Received
           1: "change", ""
           2: "change", ""

    Number of calls: 2

       95 |
       96 |           ufs.use(fs).use(Volume.fromJSON({ 'foo.js': '' }, '/tmp') as any);
    >  97 |
          | ^
       98 |           expect(ufs.existsSync(__filename)).toBe(true);
       99 |           expect(fs.existsSync(__filename)).toBe(true);
      100 |           expect(ufs.existsSync('/tmp/foo.js')).toBe(true);

      at Object.<anonymous> (src/__tests__/union.test.ts:97:42)
```

**Comment by G-Rath** [comment]
It looks like the issue is because of https://github.com/streamich/memfs/pull/902

**Comment by G-Rath** [comment]
This has now been released in 4.5.0 🎉

**Pull request merged**
