### PR TITLE
expose Readable & Writable

### LINKED ISSUE #1: Missing ReadStream and WriteStream classes
If you try and do (admittedly weird) things with graceful-fs, it expects `fs` (which can be replaced by unionfs) to have ReadStream and WriteStream.

Can you expose those on unionfs?

https://github.com/isaacs/node-graceful-fs/blob/master/graceful-fs.js#L156

### PR DESCRIPTION
**Pull request by digitalkaoz**
fixes #1

### CODE REVIEW

**Comment by streamich** [comment]
There is a way to add streams to `unionfs`, but it is not trivial.

Your implementation is obviously invalid, all it does is it creates some "placeholders".

What is the reason for doing so?

**Comment by digitalkaoz** [comment]
graceful-fs tries to get those streams (fs.prototype.ReadStream, fs.prototype.WriteStream), if they are not there it fails hard.

yes it seems wrong as it still doesnt work correctly here (just a few steps later)

**Comment by streamich** [comment]
I am OK including this hack. However this introduces a dependency:

```js
import {Readable, Writable} from "stream";
```

Which may break browser users. It has to be done somehow as to not break browser builds.

**Comment by streamich** [comment]
Maybe something like this

```js
const isBrowser = typeof __filename === 'undefined';
```

?

**Comment by digitalkaoz** [comment]
yeah made it conditional...

another question here:

i think im using it alltogether somehow wrong:

```js
const {ufs} = require('unionfs');
const {Volume} = require('memfs');
const fs = require('fs');

ufs
.use(fs)
.use(Volume.fromJSON({"foo.js": ""}, "/tmp"))

console.log(ufs.existsSync(__filename)); // false
console.log(fs.existsSync(__filename)); // true
console.log(ufs.existsSync("/tmp/foo.js")); // true
```

why does it fail when trying to stat an existing file? the in memory volume is mounted somewhere else `__filename` shouldnt be affected?!

**Comment by digitalkaoz** [comment]
@streamich any idea on this one?

**Comment by streamich** [comment]
I will take a look at it this evening.

**Comment by digitalkaoz** [comment]
@streamich thanks for merging and fixing! did you have some time to look into my example above?

**Comment by streamich** [comment]
@digitalkaoz Sorry, I keep forgetting about this, will create an issue.

**Comment by streamich** [comment]
@digitalkaoz Should be fixed here: https://github.com/streamich/unionfs/issues/10#issuecomment-350269633

Thanks for the find.

**Pull request merged**
